<x-layouts.admin-layout pageTitle="Cardápio">
    <div class="admin-page-heading"><div><p class="eyebrow">Produtos</p><h1>Cardápio</h1><p>Gerencie sabores, preços e disponibilidade sem perder o ritmo.</p></div><button class="btn-rustic" data-bs-toggle="modal" data-bs-target="#newPizza"><i class="fa-solid fa-plus"></i> Nova pizza</button></div>
    <section class="menu-admin-grid">
        @foreach ($pizzas as $pizza)
            <article class="menu-admin-card {{ !$pizza->available ? 'is-unavailable' : '' }}">
                <div class="menu-admin-image"><img src="{{ asset('assets/images/pizzas/' . ($pizza->image ?: 'pizza1.jpg')) }}" alt="{{ $pizza->name }}"><span>{{ $pizza->available ? 'Disponível' : 'Pausado' }}</span></div>
                <form method="POST" action="{{ route('admin.menu.update', $pizza) }}">@csrf @method('PATCH')
                    <div class="menu-admin-body"><div class="menu-card-title"><div><small>{{ $pizza->category }}</small><h2>{{ $pizza->name }}</h2></div>@if($pizza->featured)<i class="fa-solid fa-star" title="Destaque"></i>@endif</div>
                    <input type="hidden" name="name" value="{{ $pizza->name }}"><input type="hidden" name="category" value="{{ $pizza->category }}"><input type="hidden" name="flavor" value="{{ $pizza->flavor }}"><input type="hidden" name="image" value="{{ $pizza->image }}"><input type="hidden" name="prep_time" value="{{ $pizza->prep_time }}">
                    <div class="price-row"><label>P <input name="small_price" value="{{ $pizza->small_price }}"></label><label>M <input name="medium_price" value="{{ $pizza->medium_price }}"></label><label>G <input name="large_price" value="{{ $pizza->large_price }}"></label></div>
                    <div class="menu-card-footer"><label class="switch-label"><input type="checkbox" name="available" value="1" @checked($pizza->available)><span></span> Disponível</label><input type="hidden" name="featured" value="{{ $pizza->featured ? 1 : 0 }}"><button>Salvar</button></div></div>
                </form>
            </article>
        @endforeach
    </section>

    <div class="modal fade" id="newPizza" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><form class="modal-content rustic-modal" method="POST" action="{{ route('admin.menu.store') }}">@csrf<div class="modal-header"><div><p class="eyebrow">Novo item</p><h2>Adicionar pizza</h2></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-7"><label>Nome<input class="form-control" name="name" required></label></div><div class="col-md-5"><label>Categoria<input class="form-control" name="category" value="Tradicionais" required></label></div><div class="col-12"><label>Ingredientes<textarea class="form-control" name="flavor" rows="3" required></textarea></label></div><div class="col-md-4"><label>Preço P<input class="form-control" type="number" step=".01" name="small_price"></label></div><div class="col-md-4"><label>Preço M<input class="form-control" type="number" step=".01" name="medium_price"></label></div><div class="col-md-4"><label>Preço G<input class="form-control" type="number" step=".01" name="large_price"></label></div><div class="col-md-8"><label>Arquivo da imagem<input class="form-control" name="image" placeholder="pizza1.jpg"></label></div><div class="col-md-4"><label>Preparo (min)<input class="form-control" type="number" name="prep_time" value="25" required></label></div><div class="col-12 d-flex gap-4"><label><input type="checkbox" name="available" value="1" checked> Disponível</label><label><input type="checkbox" name="featured" value="1"> Em destaque</label></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancelar</button><button class="btn-rustic">Adicionar ao cardápio</button></div></form></div></div>
</x-layouts.admin-layout>
